version: '3.8'
services:
  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: application
      POSTGRES_PASSWORD: password
      POSTGRES_DB: learn-nestjs-prisma
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5434:5432
    container_name: learn-nestjs-prisma-postgresql