/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const UsersLazyRouteImport = createFileRoute('/users')()
const RolesLazyRouteImport = createFileRoute('/roles')()
const ProfileLazyRouteImport = createFileRoute('/profile')()
const PostsLazyRouteImport = createFileRoute('/posts')()
const PermissionsLazyRouteImport = createFileRoute('/permissions')()
const LoginLazyRouteImport = createFileRoute('/login')()
const CommentsLazyRouteImport = createFileRoute('/comments')()
const CategoriesLazyRouteImport = createFileRoute('/categories')()
const IndexLazyRouteImport = createFileRoute('/')()

const UsersLazyRoute = UsersLazyRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/users.lazy').then((d) => d.Route))
const RolesLazyRoute = RolesLazyRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/roles.lazy').then((d) => d.Route))
const ProfileLazyRoute = ProfileLazyRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))
const PostsLazyRoute = PostsLazyRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/posts.lazy').then((d) => d.Route))
const PermissionsLazyRoute = PermissionsLazyRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/permissions.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const CommentsLazyRoute = CommentsLazyRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/comments.lazy').then((d) => d.Route))
const CategoriesLazyRoute = CategoriesLazyRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/categories.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/categories': typeof CategoriesLazyRoute
  '/comments': typeof CommentsLazyRoute
  '/login': typeof LoginLazyRoute
  '/permissions': typeof PermissionsLazyRoute
  '/posts': typeof PostsLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/roles': typeof RolesLazyRoute
  '/users': typeof UsersLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/categories': typeof CategoriesLazyRoute
  '/comments': typeof CommentsLazyRoute
  '/login': typeof LoginLazyRoute
  '/permissions': typeof PermissionsLazyRoute
  '/posts': typeof PostsLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/roles': typeof RolesLazyRoute
  '/users': typeof UsersLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/categories': typeof CategoriesLazyRoute
  '/comments': typeof CommentsLazyRoute
  '/login': typeof LoginLazyRoute
  '/permissions': typeof PermissionsLazyRoute
  '/posts': typeof PostsLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/roles': typeof RolesLazyRoute
  '/users': typeof UsersLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/comments'
    | '/login'
    | '/permissions'
    | '/posts'
    | '/profile'
    | '/roles'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/comments'
    | '/login'
    | '/permissions'
    | '/posts'
    | '/profile'
    | '/roles'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/comments'
    | '/login'
    | '/permissions'
    | '/posts'
    | '/profile'
    | '/roles'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CategoriesLazyRoute: typeof CategoriesLazyRoute
  CommentsLazyRoute: typeof CommentsLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  PermissionsLazyRoute: typeof PermissionsLazyRoute
  PostsLazyRoute: typeof PostsLazyRoute
  ProfileLazyRoute: typeof ProfileLazyRoute
  RolesLazyRoute: typeof RolesLazyRoute
  UsersLazyRoute: typeof UsersLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments': {
      id: '/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof CommentsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CategoriesLazyRoute: CategoriesLazyRoute,
  CommentsLazyRoute: CommentsLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  PermissionsLazyRoute: PermissionsLazyRoute,
  PostsLazyRoute: PostsLazyRoute,
  ProfileLazyRoute: ProfileLazyRoute,
  RolesLazyRoute: RolesLazyRoute,
  UsersLazyRoute: UsersLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
